#if !HAVE_CRYPT
#define DROPBEAR_SVR_PASSWORD_AUTH 0
#endif
#define DROPBEAR_DSS 0
#define DROPBEAR_DH_GROUP1 0
#define DO_HOST_LOOKUP 1
#define DEFAULT_PATH "/bin:/sbin:/usr/bin:/usr/sbin"
#define DROPBEAR_DH_GROUP14_SHA1 0
#define DROPBEAR_ECDH 0
#define DROPBEAR_ECDSA 0
#define DROPBEAR_RSA 0
#define DROPBEAR_SHA1_HMAC 0
#define DROPBEAR_DH_GROUP16 1
#define DROPBEAR_DH_GROUP14_SHA256 0
#define DROPBEAR_SHA2_256_HMAC 0