#!/bin/sh

. /etc/profile

start()
{
    LAUNCHER_ARGS="-multifile"

    printf "Starting Application Launcher: "

    # wait for the card to initialize
    for i in `seq 1 3`;
    do
	res=$(cat /sys/class/drm/card0/*/modes 2>/dev/null | tr -d '\n')
	[ -z "$res" ] || break
	sleep 1
    done

    cd /opt/ApplicationLauncher/

    case "$res" in
	*"480x272"*)
            start-stop-daemon -S -q -b -m -p /var/run/launcher.pid \
			      --exec bin/ApplicationLauncher -- -WQVGA $LAUNCHER_ARGS
            ;;
	*)
            start-stop-daemon -S -q -b -m -p /var/run/launcher.pid \
			      --exec bin/ApplicationLauncher -- $LAUNCHER_ARGS
            ;;
    esac
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop()
{
    printf "Stopping Application Launcher: "
    start-stop-daemon -K -q -p /var/run/launcher.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    *)
	;;
esac
