#!/bin/sh
# SPDX-License-Identifier: GPL-2.0

# Setup Cgroups
echo 1 > /sys/fs/cgroup/memory.use_hierarchy

/etc/init.d/S02sysctl start

GG_LAUNCHER=/greengrass/ggc/core/greengrassd
case "${1}" in
	start | stop | restart)
		${GG_LAUNCHER} ${1}
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
